# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/subworkflows/yaml-schema.json
name: "reads_bwamem_decont"

## A description of the subworkflow and list keywords
description: Map short reads to a reference genome and remove matching reads
keywords:
  - decontamination
  - short-reads
  - mapping

    ## A list of the modules and/or subworkflows used in the subworkflow
components:
  - bwamem2/mem
  - samtools/bam2fq

## List all of the channels used as input with a description and their structure
input:
  - reads:
      type: file
      description: |
        The input channel containing the short reads
        Structure: [ val(meta), path(reads) ]
      pattern: "*.{fastq/fq}.gz"
  - ref_genome:
      type: file
      description: |
        The input channel containing the reference genome name
        Structure: path(reference_genome)
  - ref_genome_index:
      type: file
      description: |
        The input channel containing the reference genome index for bwa-mem2
        Structure: path(reference_genome_index)

## List all of the channels used as output with a descriptions and their structure
output:
  - decontaminated_reads:
      type: file
      description: |
        Channel containing the unmapped reads
        Structure: [ val(meta), path(reads) ]
      pattern: "*.fq.gz"
  - versions:
      type: file
      description: |
        File containing software versions
        Structure: [ path(versions.yml) ]
      pattern: "versions.yml"
authors:
  - "@EBI-Metagenomics"
maintainers:
  - "@EBI-Metagenomics"
