name: samtools_bam2fq
description: |
  The module uses bam2fq method from samtools to
  convert a SAM, BAM or CRAM file to FASTQ format
keywords:
  - bam2fq
  - samtools
  - fastq
tools:
  - samtools:
      description: Tools for dealing with SAM, BAM and CRAM files
      documentation: http://www.htslib.org/doc/1.1/samtools.html
      licence: ["MIT"]
input:
  - bam:
      type: file
      description: sorted BAM file
      pattern: "*_sorted.bam"
  - bai:
      type: file
      description: index of BAM file
      pattern: "*_sorted.bam.bai"
  - split:
      type: boolean
      description: |
        TRUE/FALSE value to indicate if reads should be separated into /1, /2 for paired-end, or singleton.
output:
  - reads:
      type: file
      description: |
        List of fastq files. Two files for paired-end reads and one file for single-end reads
      pattern: "*.decont.fq.gz"
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"
authors:
  - "@lescai"
maintainers:
  - "@lescai"
