# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/meta-schema.json
name: "dbcan"
description: CAZyme annotation of proteins
keywords:
  - substrate prediction
  - annotation
  - cazyme
tools:
  - "dbcan":
      description: "Standalone version of dbCAN annotation tool for automated CAZyme
        annotation"
      homepage: "https://dbcan.readthedocs.io/en/latest/"
      documentation: "https://dbcan.readthedocs.io/en/latest/"
      tool_dev_url: "https://github.com/linnabrown/run_dbcan"
      doi: "10.1093/nar/gkad328"
      licence: ["GPL v3-or-later"]
      identifier: biotools:dbcan
input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. `[ id:'test', single_end:false ]`
    - fasta:
        type: file
        description: A FASTA file containing query sequences, they can be proteins of
          contigs
        pattern: "*.{fasta,faa,fa}"
  - - meta2:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. `[ id:'test', single_end:false ]`
    - gff:
        type: file
        description: GFF file containing protein annotation information for the fasta
          file, only used then clusters are specified
        pattern: "*.gff"
  - - dbcan_db:
        type: directory
        description: dbCAN database
        pattern: "dbcan_db"
    - db_version:
        type: string
        description: The version of the dbCAN database
  - - mode:
        type: string
        enum:
          - prok
          - protein
          - meta
        description: Type of sequence input. protein=proteome; prok=prokaryote; meta=metagenome
output:
  - overview_output:
      - meta:
          type: map
          description: "Groovy Map containing sample information"
      - results/${prefix}_overview.txt.gz:
          type: file
          description: "Summarizes CAZyme predictions across tools, including SignalP results."
          pattern: "results/*_overview.txt.gz"
  - dbsub_output:
      - meta:
          type: map
          description: "Groovy Map containing sample information"
      - results/${prefix}_*.hmm.out.gz:
          type: file
          description: "Output from the dbCAN_sub run."
          pattern: "results/*.hmm.out.gz"
  - diamond_output:
      - meta:
          type: map
          description: "Groovy Map containing sample information"
      - results/${prefix}_diamond.out.gz:
          type: file
          description: "Results from the Diamond BLAST."
          pattern: "results/*_diamond.out.gz"
  - hmmer_output:
      - meta:
          type: map
          description: "Groovy Map containing sample information"
      - results/${prefix}_hmmer.out.gz:
          type: file
          description: "Output from the HMMER run."
          pattern: "results/$*_hmmer.out.gz"
  - tf_output:
      - meta:
          type: map
          description: "Groovy Map containing sample information"
      - results/${prefix}_tf.out.gz:
          type: file
          description: "Diamond BLAST output predicting Transcription Factors (TFs) for CGCFinder."
          pattern: "results/*_tf.out.gz"
  - tc_output:
      - meta:
          type: map
          description: "Groovy Map containing sample information"
      - results/${prefix}_tc.out.gz:
          type: file
          description: "Diamond BLAST output predicting Transporter Classifications (TCs) for CGCFinder."
          pattern: "results/*_tc.out.gz"
  - tp_out:
      - meta:
          type: map
          description: "Groovy Map containing sample information"
      - results/${prefix}_tp_out.gz:
          type: file
          description: "DIAMOND search result against the TCDB 9 annotated protein sequences"
          pattern: "results/*_tp.out.gz"
  - stp_out:
      - meta:
          type: map
          description: "Groovy Map containing sample information"
      - results/${prefix}_stp.out.gz:
          type: file
          description: "HMMER search result against the MiST5 compiled signal transduction protein HMMs from Pfam"
          pattern: "results/*_stp_out.gz"
  - uniinput:
      - meta:
          type: map
          description: "Groovy Map containing sample information"
      - results/${prefix}_uniInput.gz:
          type: file
          description: "The unified input file for subsequent tools, created by Prodigal if a nucleotide sequence is used."
          pattern: "results/*_uniInput.out.gz"
  - cgc_output:
      - meta:
          type: map
          description: "Groovy Map containing sample information"
      - results/${prefix}_cgc.out.gz:
          type: file
          description: "Output from the CGCFinder run."
          pattern: "results/*_cgc.out.gz"
  - cgc_gff:
      - meta:
          type: map
          description: "Groovy Map containing sample information"
      - results/${prefix}_cgc.gff.gz:
          type: file
          description: "GFF input file for CGCFinder."
          pattern: "results/*_cgc.gff.gz"
  - cgc_standard_output:
      - meta:
          type: map
          description: "Groovy Map containing sample information"
      - results/${prefix}_cgc_standard.out.gz:
          type: file
          description: "Simplified version of cgc.out, containing columns like CGC_id, Type, Contig_id, Gene_id, Start, End, Strand, and Annotation."
          pattern: "results/*_cgc.out.gz"
  - cgc_standard_output_json:
      - meta:
          type: map
          description: "Groovy Map containing sample information"
      - results/${prefix}_cgc_standard.out.json.gz:
          type: file
          description: "Simplified version of cgc.out, containing columns like CGC_id, Type, Contig_id, Gene_id, Start, End, Strand, and Annotation but in json format."
          pattern: "results/*_cgc_standard.out.json.gz"
  - synteny_pdfs:
      - meta:
          type: map
          description: "Groovy Map containing sample information"
      - results/synteny.pdf/*-syntenic.pdf.gz:
          type: file
          description: "Syntenic block alignment plots between all CGCs and PULs"
          pattern: "results/synteny.pdf/*-syntenic.pdf.gz"
  - substrate_out:
      - meta:
          type: map
          description: "Groovy Map containing sample information"
          pattern: "results/*_substrate.out.gz"
      - results/${prefix}_substrate.out.gz:
          type: file
          description: "summary of substrate prediction results for CGCs in TSV format from two approaches3 (dbCAN-PUL blast search and dbCAN-sub majority voting)"
          pattern: "results/*_substrate.out.gz"
  - versions:
      - versions.yml:
          type: file
          description: File containing software versions
          pattern: "versions.yml"
authors:
  - "@jmattock5"
  - "@mberacochea"
  - "@tgurbich"
