---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/environment-schema.json
name: "hmmer_hmmsearch"
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - "bioconda::hmmer=3.4"
