# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/meta-schema.json
name: "fraggenescanrs"
description: "FragGeneScanRs: faster gene prediction for short reads"
keywords:
  - gene
  - gene finding
  - microbial
tools:
  - "fraggenescanrs":
      description: "Rust implementation of the gene prediction model for short and error-prone
        reads"
      homepage: "https://github.com/unipept/FragGeneScanRs"
      documentation: "https://github.com/unipept/FragGeneScanRs"
      tool_dev_url: "https://github.com/unipept/FragGeneScanRs"
      doi: "10.1186/s12859-022-04736-5"
      licence: ["GPL v3-or-later"]
      identifier: biotools:fraggenescanrs

input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. `[ id:'test', single_end:false ]`
    - fasta:
        type: file
        description: Database of sequences in FASTA format
        pattern: "*.{fasta,fna,fasta.gz,fna.gz}"
  - - training_file_name:
        type: string
        enum:
          - "complete"
          - "sanger_5"
          - "sanger_10"
          - "454_5"
          - "454_10"
          - "454_30"
          - "illumina_1"
          - "illumina_5"
          - "illumina_10"
        description: The name of the file that contains the model parameters. These models are part of the tool's installation, so the name is the only information needed.
output:
  - nucleotide_fasta:
      - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'test', single_end:false ]`
          pattern: "*.ffn.gz"
      - "*.ffn.gz":
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'test', single_end:false ]`
          pattern: "*.ffn.gz"
  - amino_acid_fasta:
      - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'test', single_end:false ]`
          pattern: "*.faa.gz"
      - "*.faa.gz":
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'test', single_end:false ]`
          pattern: "*.faa.gz"
  - gene_annotations:
      - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'test', single_end:false ]`
          pattern: "*.out.gz"
      - "*.out.gz":
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'test', single_end:false ]`
          pattern: "*.out.gz"
  - gff:
      - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'test', single_end:false ]`
          pattern: "*.gff.gz"
      - "*.gff.gz":
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'test', single_end:false ]`
          pattern: "*.gff.gz"
  - versions:
      - versions.yml:
          type: file
          description: File containing software versions
          pattern: "versions.yml"

authors:
  - "@mberacochea"

maintainers:
  - "@mberacochea"
