# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/subworkflows/yaml-schema.json
name: "fasta_domainannotation"
description: Protein domain annotation
keywords:
  - protein
  - domain
  - annotation
components:
  - blast/makeblastdb
  - blast/blastp
  - interproscan
  - eggnogmapper
input:
  - ch_fasta:
      type: list
      description: |
        The input channel containing the meta id and the fasta with the proteins to annotate
        Structure: [ val(meta), path(fasta) ]
      pattern: "*.{fa/fasta/fa.gz/fasta.gz}"
  - ch_blast_fasta:
      type: file
      description: |
        The input channel containing the fasta with the protein database (e.g. UniprotSP) including their annotations, which blastp will be used against
        Structure: path(fasta)
      pattern: "*.{fa/fasta/fa.gz/fasta.gz}"
  - ch_eggnog:
      type: list
      description: |
        Input paths to eggnog folders and files required for the eggnogmapper annotation
        Structure: [ path(eggnog_db), path(eggnog_data_dir), path(diamond_db) ]
output:
  - blastp_csv:
      type: file
      description: |
        Channel containing CSV domain annotation output from blastp
        Structure: [ val(meta), path(csv) ]
      pattern: "*.csv"
  - inteproscan_tsv:
      type: file
      description: |
        Channel containing TSV domain annotation output from InterProScan
        Structure: [ val(meta), path(tsv) ]
      pattern: "*.tsv"
  - eggnogmapper_csv:
      type: file
      description: |
        Channel containing CSV domain annotation output from eggNOG-mapper
        Structure: [ val(meta), path(csv) ]
      pattern: "*.emapper.hits"
  - versions:
      type: file
      description: |
        File containing software versions
        Structure: [ path(versions.yml) ]
      pattern: "versions.yml"
authors:
  - "@vagkaratzas"
