---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/meta-schema.json
name: "mapseq2biom"
description: Process MAPseq output into biom and krona-txt formats
keywords:
  - mapseq
  - taxonomy
  - krona

tools:
  - "mapseq2biom":
      description: "Process MAPseq output into biom and krona-txt formats, uses mgnify-pipelines-toolkit as conda environment"
      homepage: "https://github.com/EBI-Metagenomics/mgnify-pipelines-toolkit"
      documentation: "https://github.com/EBI-Metagenomics/mgnify-pipelines-toolkit"
      tool_dev_url: "https://github.com/EBI-Metagenomics/mgnify-pipelines-toolkit"
      licence: ['Apache-2.0']

input:
  # Only when we have meta
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. `[ id:'sample1', single_end:false ]`
  - msq:
      type: file
      description: MAPseq output file
      pattern: "*.mseq"
  - db_fasta:
      type: file
      description: Processed reference database fasta file
      pattern: "*.{fasta, fasta.gz}"
  - db_tax:
      type: file
      description: Processed reference database taxonomy file
      pattern: "*.txt"
  - db_otu:
      type: file
      description: Processed reference database otu file
      pattern: "*.otu"
  - db_mscluster:
      type: file
      description: Pre-computed MAPseq cluster file
      pattern: "*.mscluster"
  - db_label:
      type: string
      description: Reference database label

output:
  #Only when we have meta
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. `[ id:'sample1', single_end:false ]`
  - krona_input:
      type: file
      description: Converted .txt file to be used with Krona
      pattern: "*.txt"
  - biom_out:
      type: file
      description: Converted biom file
      pattern: "*.tsv"
  - biom_notaxid_out:
      type: file
      description: Converted biom file without taxids
      pattern: "*.tsv"
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"

authors:
  - "@chrisata"
maintainers:
  - "@chrisata"
