---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/meta-schema.json
name: "taxonkit_reformat"
description: Reformat lineage in canonical ranks
keywords:
  - taxonomy
  - taxids
  - ncbi
  - lineage
tools:
  - "taxonkit":
      description: "A Cross-platform and Efficient NCBI Taxonomy Toolkit"
      homepage: "https://bioinf.shenwei.me/taxonkit/"
      documentation: "https://bioinf.shenwei.me/taxonkit/usage/#reformat"
      tool_dev_url: "https://github.com/shenwei356/taxonkit"
      doi: "10.1016/j.jgg.2021.03.006"
      licence: ["MIT"]

input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. `[ id:'sample1', single_end:false ]`

  - tsv:
      type: file
      description: Input TSV file
      pattern: "*.{tsv,tsv.gz}"

  - taxdb:
      type: file
      description: Taxonomy database unpacked from ftp://ftp.ncbi.nih.gov/pub/taxonomy/taxdump.tar.gz

output:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. `[ id:'sample1', single_end:false ]`

  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"

  - tsv:
      type: file
      description: Reformated output TSV file
      pattern: "*.{tsv}"

authors:
  - "@arajkovic"
maintainers:
  - "@arajkovic"
