# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/meta-schema.json
name: "CATCONTIGS"
description: MGnify contig taxonomy assignation using CAT"
keywords:
  - mags
  - taxonomy
  - genomics
tools:
  - "catcontigs":
      description: "CAT/BAT: tool for taxonomic classification of contigs and metagenome-assembled
        genomes (MAGs)"
      homepage: "https://github.com/MGXlab/CAT_pack"
      documentation: "https://github.com/MGXlab/CAT_pack"
      tool_dev_url: "https://github.com/MGXlab/CAT_pack"
      doi: "10.1038/s41467-024-47155-1."
      licence: ["MIT"]
      identifier: ""

input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. `[ id:'sample1', single_end:false ]`
    - contigs_fasta:
        type: file
        description: The fasta file that contains contigs
        pattern: "*.{fa,fasta}"
  - - cat_db:
        type: directory
        description: Path to directory that contains CAT database files
  - - taxonomy_db:
        type: directory
        description: Path to directory that contains CAT taxonomy files
output:
  - summary:
      - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'sample1', single_end:false ]`
      - "*_summary.txt":
          type: file
          description: Summary of the CAT classification file
          pattern: "*_summary.txt"
  - contigs_classification:
      - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'sample1', single_end:false ]`
      - "*_contig2classification_official_names.tsv":
          type: file
          description: "TSV file containing the taxonomic classification of each contig,
            cols: contig | classification | reason | lineage"
          pattern: "*_contig2classification_official_names.tsv"
  - versions:
      - versions.yml:
          type: file
          description: File containing software versions
          pattern: "versions.yml"
authors:
  - "@KateSakharova"
  - "@mberacochea"
maintainers:
  - "@KateSakharova"
  - "@mberacochea"
