---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/environment-schema.json
name: "bwamem2decontnobams"
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - bwa-mem2=2.2.1
  - samtools=1.19.2
  - htslib=1.19.1

