# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/yaml-schema.json
name: "eggnogmapper"
description: Fast genome-wide functional annotation through orthology assignment.
keywords:
  - annotation
  - orthology
  - genomics
tools:
  - "eggnogmapper":
      description: "Fast genome-wide functional annotation through orthology assignment."
      homepage: "https://github.com/eggnogdb/eggnog-mapper"
      documentation: "https://github.com/eggnogdb/eggnog-mapper/wiki"
      tool_dev_url: "https://github.com/eggnogdb/eggnog-mapper"
      doi: "10.1093/molbev/msab293"
      licence: ["AGPL v3"]
      identifier: ""

input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. `[ id:'test', single_end:false ]`
    - fasta:
        type: file
        description: Database of sequences in FASTA format
        pattern: "*.{fasta,fa,fasta.gz,fa.gz}"
  - - meta2: {}
    - annotation_hit_table:
        type: file
        description: Hits file from previous EggNOG run with Diamond
        pattern: "*.hits"
  - - eggnog_data_dir:
        type: directory
        description: Directory containing eggnog database files
        pattern: "*"
  - - eggnog_db:
        type: file
        description: The eggnog database file
        pattern: "*.db"
  - - eggnog_diamond_db:
        type: file
        description: The eggnog Diamond protein database file
        pattern: "*.dmnd"
output:
  - hits:
      - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'test', single_end:false ]`
      - "*.hits":
          type: file
          description: Tabulated file containing hits
          pattern: "*.hits"
  - annotations:
      - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'test', single_end:false ]`
      - "*.annotations":
          type: file
          description: Tabulated file containing annotations
          pattern: "*.annotations"
  - orthologs:
      - meta2:
          type: file
          description: Tabulated file containing EggNOG orthologs
          pattern: "*.seed_orthologs"
      - "*.seed_orthologs":
          type: file
          description: Tabulated file containing EggNOG orthologs
          pattern: "*.seed_orthologs"
  - versions:
      - versions.yml:
          type: file
          description: File containing software versions
          pattern: "versions.yml"
authors:
  - "@vagkaratzas"
  - "@chrisata"
