---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/yaml-schema.json
name: "blast_blastp"
description: BLASTP (Basic Local Alignment Search Tool- Protein) compares an amino acid (protein) query sequence against a protein database
keywords:
  - protein alignment
  - functional annotation
  - evolutionary analysis
tools:
  - "blast_blastp":
      description: "BLASTP (Basic Local Alignment Search Tool- Protein) compares an amino acid (protein) query sequence against a protein database"
      homepage: "https://blast.ncbi.nlm.nih.gov/Blast.cgi"
      documentation: "https://blast.ncbi.nlm.nih.gov/Blast.cgi?CMD=Web&PAGE_TYPE=Blastdocs"
      doi: "10.1016/S0022-2836(05)80360-2"
      licence: ["US-Government-Work"]

input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. `[ id:'test', single_end:false ]`

  - fasta:
      type: file
      description: Database of sequences in FASTA format
      pattern: "*.{fasta,fa,fasta.gz,fa.gz}"

  - db:
      type: directory
      description: Directory containing blast database files
      pattern: "*"

output:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. `[ id:'test', single_end:false ]`

  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"

  - csv:
      type: file
      description: CSV file with protein annotations
      pattern: "*.csv"

authors:
  - "@vagkaratzas"
