---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/yaml-schema.json
name: deeptmhmm
description: A Deep Learning Model for Transmembrane Topology Prediction and Classification
keywords:
  - sort
  - example
  - genomics
tools:
  - deeptmhmm:
      description: Deep Learning model for Transmembrane Helices protein domain prediction through the BioLib Python Client
      homepage: https://dtu.biolib.com/DeepTMHMM
      documentation: https://dtu.biolib.com/DeepTMHMM
      doi: 10.1101/2022.04.08.487609
      licence: ["MIT"]

input:
  - fasta:
      type: file
      description: Database of sequences in FASTA format
      pattern: "*.{fasta,fa,fasta.gz,fa.gz}"

output:
  - gff3:
      type: file
      description: Predicted topologies in general Feature Format Version 3
      pattern: "biolib_results/TMRs.gff3"

  - line3:
      type: file
      description: Predicted topologies of protein sequence and predicted topology information in three lines
      pattern: "biolib_results/predicted_topologies.3line"

  - md:
      type: file
      description: Markdown results file
      pattern: "biolib_results/deeptmhmm_results.md"

  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"

authors:
  - "@vagkaratzas"
