---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/environment-schema.json
name: "keggpathwayscompleteness"
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - "bioconda::kegg-pathways-completeness=1.0.4"
