---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/environment-schema.json
name: "colabfold_colabfoldbatch"
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - "bioconda::colabfold=1.5.5"
