---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/yaml-schema.json
name: "easel_eslreformat"
description: convert between sequence file formats
keywords:
  - fasta
  - format
  - convertion
tools:
  - "easel":
      description: "Easel is an ANSI C code library for computational analysis of biological sequences using probabilistic models."
      homepage: "https://github.com/EddyRivasLab/easel"
      documentation: "https://github.com/EddyRivasLab/easel"
      tool_dev_url: "https://github.com/EddyRivasLab/easel"
      licence: ["BSD"]
input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. `[ id:'test', single_end:false ]`
  - fasta:
      type: file
      description: Multiple sequence alignment file
      pattern: "*.{fasta,fa}"
  - type:
      type: string
      description: Output format type
      pattern: "fasta|hmmpgmd|a2m|afa|clustal|clustallike|pfam|phylip|phylips|psiblast|selex|stockholm"
output:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. `[ id:'test', single_end:false ]`
  - fa:
      type: file
      description: Transformed multiple sequence alignment file
      pattern: "*.fa"
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"
authors:
  - "@vagkaratzas"
