---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/environment-schema.json
name: "proovframe_map"
channels:
  - conda-forge
  - bioconda
dependencies:
  - "bioconda::proovframe=0.9.7"
