---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/meta-schema.json
name: "proovframe_map"
description: "frame-shift correction for long read (meta)genomics"
keywords:
  - "frame-shift correction"
  - "long-read sequencing"
  - "sequence analysis"
tools:
  - "proovframe":
      description: "frame-shift correction for long read (meta)genomics"
      homepage: "https://github.com/thackl/proovframe"
      documentation: "https://github.com/thackl/proovframe"
      tool_dev_url: "https://github.com/thackl/proovframe"
      doi: "10.1101/2021.08.23.457338"
      licence: ["MIT"]

input:
  # Only when we have meta
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. `[ id:'sample1', single_end:false ]`

  - faa:
      type: file
      description: "A FASTA file containing a database of guide protein sequences"
      pattern: "*.faa"
  - fasta:
      type: file
      description: "A FASTA file containing raw read nucleotide sequences"
      pattern: "*.{fasta,fa}"

output:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. `[ id:'sample1', single_end:false ]`

  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"

  - tsv:
      type: file
      description: "Output TSV file with the frameshift-aware protein to read alignments"
      pattern: "*.tsv"

authors:
  - "@manuelcarbajo"
  - "@MGS-sails"
maintainers:
  - "@manuelcarbajo"
  - "@MGS-sails"
