---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/environment-schema.json
name: "fastqutils"
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - "bioconda::fastq_utils=0.25.2"
