---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/environment-schema.json
name: dada2
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - bioconda::bioconductor-dada2=1.30.0
