# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/meta-schema.json
name: "dada2"
description: Infer Amplicon Sequence Variants (ASVs) from amplicon reads using DADA2
  package
keywords:
  - microbial taxonomy
  - amplicon sequence variant (asv)
  - amplicon sequencing
  - error correction
  - denoising

tools:
  - "dada2":
      description: "DADA2: High-resolution sample inference from Illumina amplicon data"
      homepage: "https://benjjneb.github.io/dada2/"
      documentation: "https://www.bioconductor.org/packages/3.6/bioc/manuals/dada2/man/dada2.pdf"
      tool_dev_url: "https://github.com/benjjneb/dada2"
      doi: "10.1038/nmeth.3869"
      licence: ["LGPL>=3"]
      identifier: biotools:dada2

input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. `[ id:'sample1', single_end:false ]`
    - reads:
        type: file
        description: Reads after QC and filtering
        pattern: "*.fastq"
output:
  - dada2_out:
      - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'sample1', single_end:false ]`
      - "*asvs.fasta":
          type: file
          description: Fasta file with ASV sequences
          pattern: "*asvs.fasta"
  - dada2_asv_counts:
      - "*asv_counts.tsv":
          type: file
          description: Counts for unique ASV sequences
          pattern: "*asv_counts.tsv"
  - versions:
      - versions.yml:
          type: file
          description: File containing software versions
          pattern: "versions.yml"
authors:
  - "@ochkalova"
maintainers:
  - "@ochkalova"
